### PR TITLE
Update golang to v1.23

### PR DESCRIPTION
**Pull request by frodenas**
* Upgrades Golang to v1.23
* Upgrades dependencies
* Upgrades golangci-lint to v1.60.3
* Fix linter issues

### CODE REVIEW

**Review by tenthirtyam — APPROVED** [review]
LGTM! Approving, but should waitn until the code scan completes before merge.

**Comment by BergCyrill** [comment]
@frodenas are there any plans when the next release containing this changes will be published? Since this fixes a critical severity CVE I would really appreciate a release in the very near future. Thanks!

**Comment by frodenas** [comment]
@BergCyrill Shotly, by EOD

**Comment by frodenas** [comment]
@BergCyrill Release [0.10.0](https://github.com/vmware/terraform-provider-vra/releases/tag/v0.10.0) has been just published to the Terraform Registry,

**Comment by BergCyrill** [comment]
Thank you @frodenas 
Are there any plans to publish this new version to the OpenTofu registry? Currently there is only version 0.9.0 available.

**Comment by frodenas** [comment]
OpenTofu Registry should automatically pick up new versions. I see that v0.10.0 was picked up yesterday (see commit [ba021cf](https://github.com/opentofu/registry/commit/ba021cf1c7807f9a8b2cc89ecacf01d8c424cf05)). I don't know why it is not showing up yet on the UI.

**Pull request merged**
