### PR TITLE
[issue-345] Add support of resource catalog_item_entitlement

### PR DESCRIPTION
**Pull request by mars4life**
It allows to have a new resource "catalog_item_entitlement" which allows to share a specific catalog item , and not the whole source type.

### CODE REVIEW

**Comment by mars4life** [comment]
Hi,
What can I do to unblock this merge request ?

**Comment by tenthirtyam** [comment]
It looks like the commits need to be signed-off as it's labeled dco-required.

Ryan

> @mars4life, you must sign every commit in this pull request acknowledging our Developer Certificate of Origin before your changes are merged. This can be done by adding `Signed-off-by: John Doe <john.doe@email.org>` to the last line of each Git commit message. The e-mail address used to sign must match the e-mail address of the Git author. Click [here](https://cla.vmware.com/dco) to view the Developer Certificate of Origin agreement.
> 
> - Commit 59de0cf2367498aa6e4c7cafa7db9f816b2c1b68 must be signed by mars4life@gmail.com
> - Commit 0206cb5efa1a935be7b168255a32c92de6eab95e must be signed by mars4life@gmail.com
> - Commit 331f9861dee56d2d6b2fe4d0c4a4bca5b5db854c must be signed by mars4life@gmail.com
> - Commit 09ac3dd9b787d6ad060a2b671ed65678651d8306 must be signed by mars4life@gmail.com
> - Commit 73d2c956e6900329a1c5e26394a96197951d173d must be signed by mars4life@gmail.com
> - Commit a10f404ee067b5124c0725499b22f7eaf75c6f89 must be signed by mars4life@gmail.com
> - Commit 83086e93c29bbb95801ca9f8c1ec8fd6af3ebabd must be signed by mars4life@gmail.com
> - Commit 488991f4caa8477ffe0ec56268ef1fc69595283c must be signed by mars4life@gmail.com
> - Commit 17632145a8fd6b42b7569541f4bfd5369a4928a0 must be signed by mars4life@gmail.com
>

**Comment by mars4life** [comment]
Hello,
All commits have been signed I think.
Am I wrong ?
image

**Comment by tenthirtyam** [comment]
You'll need to amend the commits on the branch: `https://github.com/mars4life/terraform-provider-vra/tree/mars4life-issue345`

For example, 

Set your email on the branch. For example:
```bash
$ terraform-provider-vra (mars4life-issue345)> git config user.email mars4life@gmail.com
```

Verify the email on the branch. For example:
```bash
$ terraform-provider-vra (mars4life-issue345)> git config --local --list
```

You'll then need to amend the commits, with the sign-off. For example:

```bash
$ terraform-provider-vra (mars4life-issue345)> git commit --amend --author="Amakou MBATA <mars4life@gmail.com>"
```
>Note: You may need to ammend all 9 commits. with `git rebase -i HEAD~9`. Learn more at https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message.

Then push the updates back upstream:

```bash
$ terraform-provider-vra (mars4life-issue345)> git push --force-with-lease origin mars4life-issue345
```

In the future, you can set the email on the fork/branch and then add the followig to commit messages before pushing.

```bash
Signed-off-by: Amakou MBATA <mars4life@gmail.com>
```

Hope this helps,
Ryan

**Comment by fmosti** [comment]
Any chance somebody can review so this feature so can be released?
I will personally appreciate it very much :)

**Comment by tenthirtyam** [comment]
Superseded by https://github.com/vmware/terraform-provider-vra/pull/346.

**Pull request closed without merging**
