### PR TITLE
Added install docs

### PR DESCRIPTION
**Pull request by cars**
markdown doc to help people trying to install the provider

Signed-off-by: Carlos Tronco <cars@lostroncos.org>

### CODE REVIEW

**Comment by mdittbrenner215** [comment]
Will the documents be added on how to build from source

Go get https://url

Then go to directory

Go build -o /to/dir

**Comment by dmettem** [comment]
@cars - Thanks for the PR and also addressing the previous comments. Let me know if you want to address @mdittbrenner215's comment about documentation for building from source. If not, I will merge this PR and will address that separately.

**Comment by mdittbrenner215** [comment]
I just got internal company approval to be able to contribute so i can do a PR at some point to add documentation and samples.

**Comment by markpeek** [comment]
Thanks @cars!

**Pull request merged**
