### PR TITLE
Updates to web Docs for correct information on Placement Policy detail

### PR DESCRIPTION
**Pull request by thecloudxpert**
signed by christopher.lewis@thecloudxpert.net

### CODE REVIEW

**Comment by thecloudxpert** [comment]
signed by christopher.lewis@thecloudxpert.net

**Review by tenthirtyam — APPROVED** [review]
Looks good to me as @thecloudxpert is correct.  An ID from `data.vra_region` is not used, only `DEFAULT`, `SPREAD`, or `BINPACK` are valid values.

**Comment by tenthirtyam** [comment]
@thecloudxpert Can you amend the two commits to sign-off with the the noted email?

Ryan

**Comment by frodenas** [comment]
Thanks @thecloudxpert for this PR. Your changes have been incorporated into https://github.com/vmware/terraform-provider-vra/pull/391.

**Pull request closed without merging**
